server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
spring:
  security:
    user:
      password: root
      name: root
      roles: #multiple roles
        - admin
        - user