spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=sampledbjava;encrypt=false;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port:8080}
    title: API Document
    version: 1.0.0

