server:
  port: 8001

player:
  age: 20
  address: HCM
  maps: {k1: v1, k2: v2}   # kieu map
  lists:     # kieu lists
    - list1 
    - list2
  isActive: true     # kieu boolean
  birth: 2024/08/08  # kieu date
database:
  host: host
  username: username
  port: 3306
  password: password

spring:
  profiles:
    active: pro  # dung de set profile dung goi nao de chay file yaml
