spring:
  application:
    name: springboot-nyano
  datasource:
    url: jdbc:mysql://localhost:3307/shopdevgo
    username: root
    password: Tuong2005@
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      #none : ko có cấu hình bỏ qua, an toàn , ko cho hibernate can thiệp vào DB
      #validate: hibernate kiểm tra lược đồ CSDL của mình có khớp với các đối tượng trong entity hay 0
       # nếu khác thì sẽ ném exception
      #create  tạo và xóa lại lược đồ CSDL lại từ đầu -> tất cả xóa phải tạo lại (Nguy Hiểm nhất)
      #createdrop : dừng lại sẽ xóa
      #update: tự động cập nhật CSDL khớp với Entity , tiện khi thay đổi cấu trúc Table
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: monsterminecraft2005@gmail.com
    password: jcjl dxba gezr alrr
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

